name: Build ElasticBeastalk

on:
    push:
      branches:
        - main
      paths:
        - .github/workflows/build_elasticbeanstalk.yaml
        - ".github/workflows"
  
jobs:
  build: 
     runs-on: ubuntu-latest
 
    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v3
      with:
        name: nodejsbasic
    
    - name: Deploy to Elastic Beanstalk
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          EB_ENV_NAME: ${{ secrets.EB_ENV_NAME }}
          EB_APP_NAME: ${{ secrets.EB_APP_NAME }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      run: |
        VERSION_LABEL="${{ github.sha }}-$(date +%s)"
        aws elasticbeanstalk create-application-version \
          --application-name ${{ secrets.EB_APP_NAME }} \
          --version-label $VERSION_LABEL \
          --source-bundle S3Bucket=${{ secrets.S3_BUCKET_NAME }},S3Key=nodejsbasic.zip
        aws elasticbeanstalk update-environment \
          --environment-name ${{ secrets.EB_ENV_NAME }} \
          --version-label $VERSION_LABEL